apiVersion: v1
kind: ConfigMap
metadata:
  name: terraformrc
  namespace: atlantis
data:
  .terraformrc: |
    provider_installation {
      network_mirror {
        url = "https://terraform-mirror.yandexcloud.net/"
        include = ["registry.terraform.io/*/*"]
      }
      direct {
        exclude = ["registry.terraform.io/*/*"]
      }
    }
